### ISSUE TITLE
Comet Blue SilverCrest 

### ISSUE THREAD

**Issue by Barneybaer84** [fhem/CometBlueBTLE#2]
Neuste Version, Temperatur wird nicht mehr angezeigt bzw geändert.
Auszug aus dem Log

[code] 2018.03.16 18:59:30 3: CometBlueBTLE (WZ_Heizung) - CreateParamGatttool erstes if
2018.03.16 18:59:31 3: CometBlueBTLE (WZ_Heizung) - CreateParamGatttool zweites if
2018.03.16 18:59:32 3: CometBlueBTLE (WZ_Heizung) - ExecGatttool_Done: JSON error while request: malformed JSON string, neither array, object, number, string or atom, at character offset 0 (before "HASH(0x271bf60)") at ./FHEM/74_CometBlueBTLE.pm line 633.

2018.03.16 18:59:32 3: CometBlueBTLE (WZ_Heizung) - ProcessingNotification: handle 0x3d - Noch in Queue: 0
2018.03.16 19:00:28 3: CometBlueBTLE (WZ_Heizung) - CreateParamGatttool erstes if
2018.03.16 19:00:30 3: CometBlueBTLE (WZ_Heizung) - CreateParamGatttool drittes if
2018.03.16 19:00:30 3: CometBlueBTLE (WZ_Heizung) - CreateParamGatttool zweites if
2018.03.16 19:00:30 3: CometBlueBTLE (WZ_Heizung) - ExecGatttool_Done: JSON error while request: malformed JSON string, neither array, object, number, string or atom, at character offset 0 (before "HASH(0x271bf60)") at ./FHEM/74_CometBlueBTLE.pm line 633.

2018.03.16 19:00:30 3: CometBlueBTLE (WZ_Heizung) - ProcessingNotification: handle 0x3d - Noch in Queue: 0[/code]

Und ein List
[code]
Internals:
   BTMAC      45:EB:20:E9:0C:6A
   DEF        45:EB:20:E9:0C:6A
   INTERVAL   1800
   NAME       WZ_Heizung
   NOTIFYDEV  global,WZ_Heizung
   NR         80
   NTFY_ORDER 50-WZ_Heizung
   STATE      T: 0 desired: 0
   TYPE       CometBlueBTLE
   VERSION    0.1.39
   loglevel   4
   READINGS:
     2018-03-16 18:55:50   battery         low
     2018-03-16 18:55:50   batteryLevel    0
     2018-03-16 18:55:51   desired-temp    0
     2018-01-24 23:46:35   devicename      Comet Blue
     2018-01-24 23:45:53   firmware        0.0.10
     2018-03-16 19:00:30   lastChangeBy    FHEM
     2018-03-11 16:11:56   lastGattError   Device or resource busy (16)
     2018-03-16 18:55:51   measured-temp   0
     2018-03-16 19:00:30   state           T: 0 desired: 0
     2018-03-16 18:55:51   tempComfort     0
     2018-03-16 18:55:51   tempEco         0
     2018-02-28 00:45:40   tempOffset      0
     2018-03-16 18:55:51   winOpnPeriod    0
     2018-01-24 23:46:12   winOpnSensitivity low
   helper:
     CallBattery 0
     updateTimeCallBattery 1521222950.62456
     updateTimestampCallBattery 2018-03-16 18:55:50
     writePin   0
     paramGatttool:
       handle     0x3d
       mod        write
       value      00380000000c00
   tempListsHandleQueue:
Attributes:
   alias      Heizung
   hciDevice  hci0
   interval   1800
   model      SilverCrest
   pin        0
   room       Wohnzimmer[/code]

**Comment by CoolTuxNet** [comment]
Bitte einmal die neue Version testen

**Comment by Barneybaer84** [comment]
Neues Log

2018.03.16 21:36:10 3: CometBlueBTLE (WZ_Heizung) - CreateParamGatttool zweites if
2018.03.16 21:36:10 3: CometBlueBTLE (WZ_Heizung) - ExecGatttool_Done: JSON error while request: malformed JSON string, neither array, object, number, string or atom, at character offset 0 (before "HASH(0x2163820)") at ./FHEM/74_CometBlueBTLE.pm line 633.

2018.03.16 21:36:10 3: CometBlueBTLE (WZ_Heizung) - ProcessingNotification: handle 0x3f - Noch in Queue: 0
2018.03.16 21:36:10 1: PERL WARNING: Use of uninitialized value $notification in substitution (s///) at ./FHEM/74_CometBlueBTLE.pm line 728.
2018.03.16 21:36:10 3: eval: {CometBlueBTLE_ExecGatttool_Done('WZ_Heizung|45:EB:20:E9:0C:6A|ok|read|0x3f|HASH(0x2163820)')}
2018.03.16 21:36:10 1: PERL WARNING: Use of uninitialized value $notification in concatenation (.) or string at ./FHEM/74_CometBlueBTLE.pm line 730.
2018.03.16 21:36:10 3: eval: {CometBlueBTLE_ExecGatttool_Done('WZ_Heizung|45:EB:20:E9:0C:6A|ok|read|0x3f|HASH(0x2163820)')}
2018.03.16 21:36:10 1: PERL WARNING: Use of uninitialized value $notification in concatenation (.) or string at ./FHEM/74_CometBlueBTLE.pm line 731.
2018.03.16 21:36:10 3: eval: {CometBlueBTLE_ExecGatttool_Done('WZ_Heizung|45:EB:20:E9:0C:6A|ok|read|0x3f|HASH(0x2163820)')}
2018.03.16 21:36:10 3: CometBlueBTLE (WZ_Heizung) - CreateParamGatttool erstes if
2018.03.16 21:36:11 3: CometBlueBTLE (WZ_Heizung) - CreateParamGatttool zweites if
2018.03.16 21:36:11 3: CometBlueBTLE (WZ_Heizung) - ExecGatttool_Done: JSON error while request: malformed JSON string, neither array, object, number, string or atom, at character offset 0 (before "HASH(0x2163820)") at ./FHEM/74_CometBlueBTLE.pm line 633.

2018.03.16 21:36:11 3: CometBlueBTLE (WZ_Heizung) - ProcessingNotification: handle 0x3d - Noch in Queue: 0
2018.03.16 21:36:11 1: PERL WARNING: Use of uninitialized value $notification in split at ./FHEM/74_CometBlueBTLE.pm line 748.
2018.03.16 21:36:11 3: eval: {CometBlueBTLE_ExecGatttool_Done('WZ_Heizung|45:EB:20:E9:0C:6A|ok|read|0x3d|HASH(0x2163820)')}
2018.03.16 21:36:11 1: PERL WARNING: Use of uninitialized value $payload[0] in concatenation (.) or string at ./FHEM/74_CometBlueBTLE.pm line 762.
2018.03.16 21:36:11 3: eval: {CometBlueBTLE_ExecGatttool_Done('WZ_Heizung|45:EB:20:E9:0C:6A|ok|read|0x3d|HASH(0x2163820)')}
2018.03.16 21:36:11 1: PERL WARNING: Use of uninitialized value $payload[1] in concatenation (.) or string at ./FHEM/74_CometBlueBTLE.pm line 763.
2018.03.16 21:36:11 3: eval: {CometBlueBTLE_ExecGatttool_Done('WZ_Heizung|45:EB:20:E9:0C:6A|ok|read|0x3d|HASH(0x2163820)')}
2018.03.16 21:36:11 1: PERL WARNING: Use of uninitialized value $payload[2] in concatenation (.) or string at ./FHEM/74_CometBlueBTLE.pm line 764.
2018.03.16 21:36:11 3: eval: {CometBlueBTLE_ExecGatttool_Done('WZ_Heizung|45:EB:20:E9:0C:6A|ok|read|0x3d|HASH(0x2163820)')}
2018.03.16 21:36:11 1: PERL WARNING: Use of uninitialized value $payload[3] in concatenation (.) or string at ./FHEM/74_CometBlueBTLE.pm line 765.
2018.03.16 21:36:11 3: eval: {CometBlueBTLE_ExecGatttool_Done('WZ_Heizung|45:EB:20:E9:0C:6A|ok|read|0x3d|HASH(0x2163820)')}
2018.03.16 21:36:11 1: PERL WARNING: Use of uninitialized value $payload[4] in pattern match (m//) at ./FHEM/74_CometBlueBTLE.pm line 767.
2018.03.16 21:36:11 3: eval: {CometBlueBTLE_ExecGatttool_Done('WZ_Heizung|45:EB:20:E9:0C:6A|ok|read|0x3d|HASH(0x2163820)')}
2018.03.16 21:36:11 1: PERL WARNING: Use of uninitialized value $payload[4] in concatenation (.) or string at ./FHEM/74_CometBlueBTLE.pm line 770.
2018.03.16 21:36:11 3: eval: {CometBlueBTLE_ExecGatttool_Done('WZ_Heizung|45:EB:20:E9:0C:6A|ok|read|0x3d|HASH(0x2163820)')}
2018.03.16 21:36:11 1: PERL WARNING: Use of uninitialized value $payload[5] in concatenation (.) or string at ./FHEM/74_CometBlueBTLE.pm line 773.
2018.03.16 21:36:11 3: eval: {CometBlueBTLE_ExecGatttool_Done('WZ_Heizung|45:EB:20:E9:0C:6A|ok|read|0x3d|HASH(0x2163820)')}
2018.03.16 21:36:11 1: PERL WARNING: Use of uninitialized value $payload[6] in concatenation (.) or string at ./FHEM/74_CometBlueBTLE.pm line 774.
2018.03.16 21:36:11 3: eval: {CometBlueBTLE_ExecGatttool_Done('WZ_Heizung|45:EB:20:E9:0C:6A|ok|read|0x3d|HASH(0x2163820)')}
2018.03.16 21:36:11 1: PERL WARNING: Use of uninitialized value $v in concatenation (.) or string at ./FHEM/74_CometBlueBTLE.pm line 871.
2018.03.16 21:36:11 3: eval: {CometBlueBTLE_ExecGatttool_Done('WZ_Heizung|45:EB:20:E9:0C:6A|ok|read|0x3d|HASH(0x2163820)')}
2018.03.16 21:36:11 1: PERL WARNING: Use of uninitialized value $v in string ne at ./FHEM/74_CometBlueBTLE.pm line 872.
2018.03.16 21:36:11 3: eval: {CometBlueBTLE_ExecGatttool_Done('WZ_Heizung|45:EB:20:E9:0C:6A|ok|read|0x3d|HASH(0x2163820)')}
2018.03.16 21:36:11 1: PERL WARNING: Use of uninitialized value $value in string eq at fhem.pl line 4492.
2018.03.16 21:36:11 3: eval: {CometBlueBTLE_ExecGatttool_Done('WZ_Heizung|45:EB:20:E9:0C:6A|ok|read|0x3d|HASH(0x2163820)')}

**Comment by Barneybaer84** [comment]
Ach ja und hier https://forum.fhem.de/index.php/topic,61628.msg755261.html#msg755261
hatte ich noch die tempLists für SilverCrest hinzugefügt.
