### ISSUE TITLE
desired-temp reset auf 0 über Nacht

### ISSUE THREAD

**Issue by aut0** [fhem/CometBlueBTLE#3]
Hallo,

ich habe 3 Comet Blue Nachbauten von Xavax an meinem fhem server. Eigentlich scheint auch alles zu funktionieren, außer controlManu, wo ich immer error als state bekomme. Wenn ich jetzt abends die desired-temp auf 22 Grad setze wird die Heizung eingeschaltet. Die Heizung wird nachts allerdings zentral abgeschaltet. Ich würde erwarten, dass der Regler das Ventil die ganze Nacht offen lässt und morgens wenn die Heizung wieder angeht der Raum auf 22 Grad aufgeheizt wird. Das ist aber nicht der Fall. Morgens steht die desired-temp immer auf 0 ohne das ich was geändert habe. Ich hab mal ein bisschen über den Code geschaut, aber nichts auffälliges gefunden. Mir ist aufgefallen, dass writePin eine semaphore implementieren soll, ich weiß aber nicht was passiert, wenn mehrere Comet Blue Instanzen um gatttool konkurieren. Vielleicht ist das Teil des Problems. Ist aber nur eine Vermutung.
Hast du vielleicht eine Idee was ich machen könnte, um das genauer zu analysieren?

Danke,
aut0

**Comment by CoolTuxNet** [comment]
Hallo,

Das einzige was mir dazu einfällt ist die Thermostate einmal auf verbose 5 zu stellen über Nacht und dann schauen wir mal was wir so bekommen.

Grüße

**Comment by aut0** [comment]
Hallo,

ich habs gefunden. Es war auf dem Thermostat noch ein Zeitplan eingestellt. Also alles in Ordnung.
Ich hab noch gesehen, dass es stellen im code gibt wo "another process is running try again later" zurückgegeben wird. Das kann dazu führen, dass die Heizung nicht von einem Timer eingeschaltet wird. Spricht etwas dagegen hier busy wait zu machen und writePin zu pollen bis der andere fertig ist und dann die gewünschte aktion auszuführen?

Gruß

**Comment by CoolTuxNet** [comment]
Das mit dem another process is running bezieht sich auf ein gatttool Prozess mit der selben MAC Adresse. Ändern kann man das nicht. Es wird versucht in einer Schleife 10 mal zu prüfen ob ein anderer Prozess läuft mit jeweils 0.5s Pause.
